# Generated by Django 5.2.8 on 2025-11-18 10:53

import django.db.models.deletion
import students.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_number', models.PositiveIntegerField(default=students.models.generate_student_number, editable=False, unique=True, verbose_name='학생 고유 번호')),
                ('name', models.CharField(max_length=100, verbose_name='이름')),
                ('school', models.CharField(blank=True, max_length=100, null=True, verbose_name='학교')),
                ('grade', models.CharField(choices=[('K5', 'K5'), ('K6', 'K6'), ('K7', 'K7'), ('K8', 'K8'), ('K9', 'K9'), ('K10', 'K10'), ('K11', 'K11'), ('K12', 'K12')], max_length=3, verbose_name='학년')),
                ('student_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='학생 전화번호')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='이메일 주소')),
                ('gender', models.CharField(choices=[('M', '남'), ('F', '여')], max_length=10, verbose_name='성별')),
                ('parent_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='부모님 전화번호')),
                ('receipt_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='현금 영수증 용 번호')),
                ('interview_date', models.DateField(blank=True, null=True, verbose_name='인터뷰 날짜')),
                ('interview_score', models.CharField(blank=True, max_length=50, null=True, verbose_name='인터뷰 기본 성적')),
                ('interview_info', models.TextField(blank=True, null=True, verbose_name='인터뷰 정보')),
                ('first_class_date', models.DateField(blank=True, null=True, verbose_name='첫 수업 날짜')),
                ('last_class_date', models.DateField(blank=True, null=True, verbose_name='그만 둔 날짜')),
                ('misc', models.TextField(blank=True, null=True, verbose_name='기타')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
            ],
            options={
                'verbose_name': '학생',
                'verbose_name_plural': '학생 목록',
            },
        ),
        migrations.CreateModel(
            name='StudentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=students.models.student_file_upload_path, verbose_name='첨부 파일')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='파일 설명')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='업로드 날짜')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='students.student', verbose_name='학생')),
            ],
            options={
                'verbose_name': '학생 파일',
                'verbose_name_plural': '학생 파일 목록',
            },
        ),
        migrations.CreateModel(
            name='StudentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='일정 제목')),
                ('description', models.TextField(blank=True, null=True, verbose_name='일정 내용')),
                ('schedule_date', models.DateField(verbose_name='일정 날짜')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='시작 시간')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='종료 시간')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='students.student', verbose_name='학생')),
            ],
            options={
                'verbose_name': '학생 개별 일정',
                'verbose_name_plural': '학생 개별 일정 목록',
            },
        ),
    ]
