# Generated by Django 5.2.8 on 2025-11-24 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_unpaid_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('ATTENDING', '재원 (다니는 중)'), ('BREAK', '휴원 (잠시 쉼)'), ('DISCHARGED', '퇴원 (그만둠)'), ('GRADUATED', '졸업')], default='ATTENDING', max_length=20, verbose_name='재원 상태'),
        ),
    ]
