# Generated by Django 5.2.8 on 2025-11-22 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0002_student_unpaid_amount'),
        ('teachers', '0002_teacherpaymentrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='수업명')),
                ('tuition_fee', models.PositiveIntegerField(default=0, verbose_name='수강료(월)')),
                ('schedule', models.CharField(blank=True, max_length=100, null=True, verbose_name='수업 시간')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='개강일')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='종강일')),
                ('is_active', models.BooleanField(default=True, verbose_name='진행 중 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('students', models.ManyToManyField(blank=True, related_name='enrolled_classes', to='students.student', verbose_name='수강생 목록')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teachers.teacher', verbose_name='담당 교사')),
            ],
            options={
                'verbose_name': '수업',
                'verbose_name_plural': '수업 목록',
                'ordering': ['-is_active', 'name'],
            },
        ),
    ]
