# Generated by Django 5.2.8 on 2025-11-22 21:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_alter_classinfo_schedule'),
        ('students', '0002_student_unpaid_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='TuitionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_date', models.DateField(default=django.utils.timezone.now, verbose_name='청구일')),
                ('amount', models.PositiveIntegerField(verbose_name='청구 금액')),
                ('month', models.CharField(blank=True, max_length=20, verbose_name='해당 월')),
                ('is_paid', models.BooleanField(default=False, verbose_name='납부 여부')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='납부일')),
                ('memo', models.CharField(blank=True, max_length=255, null=True, verbose_name='비고')),
                ('class_info', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logs', to='classes.classinfo', verbose_name='수업')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tuition_logs', to='students.student', verbose_name='학생')),
            ],
            options={
                'verbose_name': '수강료 내역',
                'verbose_name_plural': '수강료 내역',
                'ordering': ['-charge_date'],
            },
        ),
    ]
