# Generated by Django 5.2.8 on 2025-11-25 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_tuitionlog'),
        ('students', '0003_student_status'),
        ('teachers', '0002_teacherpaymentrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='날짜')),
                ('students', models.ManyToManyField(blank=True, related_name='assigned_classes', to='students.student', verbose_name='배정된 학생들')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_assignments', to='teachers.teacher')),
            ],
            options={
                'verbose_name': '일일 교사 배정',
                'unique_together': {('date', 'teacher')},
            },
        ),
        migrations.CreateModel(
            name='DailySpecialStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('status_type', models.CharField(choices=[('ABSENT', '결석'), ('EXCEPTION', '예외'), ('LATE', '지각'), ('SPECIAL', '특이사항')], max_length=20)),
                ('students', models.ManyToManyField(blank=True, related_name='daily_statuses', to='students.student')),
            ],
            options={
                'verbose_name': '일일 특수 상태',
                'unique_together': {('date', 'status_type')},
            },
        ),
        migrations.CreateModel(
            name='TeacherAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='휴무 날짜')),
                ('reason', models.CharField(blank=True, max_length=100, verbose_name='사유')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='teachers.teacher')),
            ],
            options={
                'unique_together': {('teacher', 'date')},
            },
        ),
    ]
