# Generated by Django 5.2.8 on 2025-11-25 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_dailyassignment_dailyspecialstatus_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailyspecialstatus',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='dailyspecialstatus',
            name='students',
        ),
        migrations.AlterUniqueTogether(
            name='teacheravailability',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='teacheravailability',
            name='teacher',
        ),
        migrations.DeleteModel(
            name='DailyAssignment',
        ),
        migrations.DeleteModel(
            name='DailySpecialStatus',
        ),
        migrations.DeleteModel(
            name='TeacherAvailability',
        ),
    ]
