# Generated by Django 5.2.8 on 2025-11-20 10:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='교재명')),
                ('isbn', models.CharField(max_length=50, unique=True, verbose_name='바코드(ISBN)')),
                ('author', models.CharField(blank=True, max_length=100, null=True, verbose_name='저자')),
                ('publisher', models.CharField(blank=True, max_length=100, null=True, verbose_name='출판사')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='판매 가격')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='재고 수량')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
            ],
            options={
                'verbose_name': '교재',
                'verbose_name_plural': '교재 목록',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='BookSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_date', models.DateField(default=django.utils.timezone.now, verbose_name='판매/지급일')),
                ('price', models.PositiveIntegerField(verbose_name='판매 당시 가격')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='수량')),
                ('is_paid', models.BooleanField(default=False, verbose_name='결제 완료 여부')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='결제일')),
                ('memo', models.CharField(blank=True, max_length=255, null=True, verbose_name='비고')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='bookstore.book', verbose_name='교재')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_sales', to='students.student', verbose_name='학생')),
            ],
            options={
                'verbose_name': '교재 판매 내역',
                'verbose_name_plural': '교재 판매 내역',
                'ordering': ['-sale_date'],
            },
        ),
    ]
