# Generated by Django 5.2.8 on 2025-11-20 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cost_price',
            field=models.PositiveIntegerField(default=0, verbose_name='입고 가격'),
        ),
        migrations.AddField(
            model_name='book',
            name='original_price',
            field=models.PositiveIntegerField(default=0, verbose_name='정상 가격'),
        ),
    ]
