# Generated by Django 5.2.8 on 2025-11-20 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0002_book_cost_price_book_original_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookStockLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='입고 수량')),
                ('cost_price', models.PositiveIntegerField(verbose_name='입고 단가')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='입고일')),
                ('memo', models.CharField(blank=True, max_length=255, null=True, verbose_name='비고')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_logs', to='bookstore.book', verbose_name='교재')),
            ],
            options={
                'verbose_name': '입고 기록',
                'verbose_name_plural': '입고 기록',
                'ordering': ['-created_at'],
            },
        ),
    ]
