# Generated by Django 5.2.8 on 2025-11-20 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0003_bookstocklog'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='상호명(법인명)')),
                ('registration_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='사업자 등록번호')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='전화번호')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='주소')),
                ('bank_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='은행명')),
                ('account_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='계좌번호')),
                ('account_owner', models.CharField(blank=True, max_length=50, null=True, verbose_name='예금주')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
            ],
            options={
                'verbose_name': '구매처',
                'verbose_name_plural': '구매처 목록',
            },
        ),
        migrations.AlterModelOptions(
            name='bookstocklog',
            options={'ordering': ['-created_at'], 'verbose_name': '재고 기록', 'verbose_name_plural': '재고 기록'},
        ),
        migrations.AddField(
            model_name='bookstocklog',
            name='payment_date',
            field=models.DateField(blank=True, null=True, verbose_name='날짜'),
        ),
        migrations.AddField(
            model_name='bookstocklog',
            name='total_payment',
            field=models.PositiveIntegerField(default=0, verbose_name='총액'),
        ),
        migrations.AlterField(
            model_name='bookstocklog',
            name='cost_price',
            field=models.PositiveIntegerField(verbose_name='단가'),
        ),
        migrations.AlterField(
            model_name='bookstocklog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='기록일'),
        ),
        migrations.AlterField(
            model_name='bookstocklog',
            name='quantity',
            field=models.IntegerField(verbose_name='수량 (입고/반품)'),
        ),
        migrations.AddField(
            model_name='bookstocklog',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookstore.booksupplier', verbose_name='구매처'),
        ),
    ]
