# Generated by Django 5.2.8 on 2025-11-20 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0004_booksupplier_alter_bookstocklog_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookstore.booksupplier', verbose_name='주거래 구매처'),
        ),
    ]
