# Generated by Django 5.2.8 on 2025-11-20 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0005_book_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookstocklog',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='정산 완료 여부'),
        ),
    ]
