# Generated by Django 5.2.8 on 2025-11-22 18:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0006_bookstocklog_is_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookstocklog',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='입고/반품일'),
        ),
    ]
