# Generated by Django 5.2.8 on 2025-11-22 18:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0007_alter_bookstocklog_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booksupplier',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='등록일(입고일)'),
        ),
    ]
