# Generated by Django 5.2.8 on 2025-11-22 19:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0009_alter_book_created_at_alter_booksupplier_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booksale',
            name='sale_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='판매일(지급일)'),
        ),
    ]
