# Generated by Django 5.2.8 on 2025-11-24 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0010_alter_booksale_sale_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='memo',
            field=models.TextField(blank=True, null=True, verbose_name='비고'),
        ),
    ]
