# Generated by Django 5.2.8 on 2025-11-18 12:35

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='이름')),
                ('gender', models.CharField(choices=[('M', '남'), ('F', '여')], max_length=10, verbose_name='성별')),
                ('phone', models.CharField(max_length=20, verbose_name='전화번호')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='이메일')),
                ('hire_date', models.DateField(default=django.utils.timezone.now, verbose_name='입사일')),
                ('resign_date', models.DateField(blank=True, null=True, verbose_name='퇴사일')),
                ('base_pay', models.PositiveIntegerField(default=0, verbose_name='급여 기준(시급/건별)')),
                ('extra_pay', models.PositiveIntegerField(default=0, verbose_name='추가 급여')),
                ('bank_name', models.CharField(max_length=50, verbose_name='거래은행')),
                ('account_number', models.CharField(max_length=50, verbose_name='급여계좌번호')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
            ],
            options={
                'verbose_name': '교사',
                'verbose_name_plural': '교사 목록',
            },
        ),
        migrations.CreateModel(
            name='TeacherUnavailable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='근무 불가 날짜')),
                ('reason', models.CharField(blank=True, max_length=200, null=True, verbose_name='사유')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unavailable_dates', to='teachers.teacher', verbose_name='교사')),
            ],
            options={
                'verbose_name': '근무 불가 일정',
                'verbose_name_plural': '근무 불가 일정 목록',
            },
        ),
        migrations.CreateModel(
            name='TeacherWorkRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='근무 날짜')),
                ('start_time', models.TimeField(default=datetime.time(18, 0), verbose_name='시작 시간')),
                ('end_time', models.TimeField(default=datetime.time(20, 0), verbose_name='종료 시간')),
                ('memo', models.CharField(blank=True, max_length=200, null=True, verbose_name='비고')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_records', to='teachers.teacher', verbose_name='교사')),
            ],
            options={
                'verbose_name': '근무 기록',
                'verbose_name_plural': '근무 기록 목록',
                'ordering': ['-date'],
            },
        ),
    ]
