# Generated by Django 5.2.8 on 2025-11-18 17:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherPaymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='년도')),
                ('month', models.IntegerField(verbose_name='월')),
                ('amount_paid', models.PositiveIntegerField(verbose_name='실제 지급액')),
                ('payment_date', models.DateField(default=django.utils.timezone.now, verbose_name='지급일')),
                ('is_paid', models.BooleanField(default=True, verbose_name='지급 완료 여부')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='teachers.teacher', verbose_name='교사')),
            ],
            options={
                'verbose_name': '급여 지급 기록',
                'verbose_name_plural': '급여 지급 기록',
                'ordering': ['-payment_date'],
                'unique_together': {('teacher', 'year', 'month')},
            },
        ),
    ]
