# Generated by Django 5.2.8 on 2025-11-25 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_teacherpaymentrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='status',
            field=models.CharField(choices=[('ACTIVE', '재직'), ('RESIGNED', '퇴직'), ('LEAVE', '휴직')], default='ACTIVE', max_length=10, verbose_name='상태'),
        ),
    ]
