# Generated by Django 5.2.8 on 2025-11-25 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0003_student_status'),
        ('teachers', '0002_teacherpaymentrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='날짜')),
                ('remarks', models.TextField(blank=True, verbose_name='특이사항')),
                ('absent_students', models.ManyToManyField(blank=True, related_name='daily_absent', to='students.student', verbose_name='결석생')),
                ('exception_students', models.ManyToManyField(blank=True, related_name='daily_exception', to='students.student', verbose_name='예외생')),
                ('late_students', models.ManyToManyField(blank=True, related_name='daily_late', to='students.student', verbose_name='지각생')),
            ],
        ),
        migrations.CreateModel(
            name='DailySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='날짜')),
                ('is_day_off', models.BooleanField(default=False, verbose_name='휴무 여부')),
                ('assigned_students', models.ManyToManyField(blank=True, related_name='daily_assigned', to='students.student', verbose_name='배정 학생')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_schedules', to='teachers.teacher', verbose_name='담당 교사')),
            ],
            options={
                'unique_together': {('date', 'teacher')},
            },
        ),
    ]
