# Generated by Django 5.2.8 on 2025-11-25 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyschedule',
            name='is_day_off',
        ),
    ]
